version: '3.8'

services:
  db:
    container_name: restazure
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=restapicuccos
      - POSTGRES_DB=rest
    
